name: Publish multiarch postgres-operator image on ghcr.io

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

on:
  push:
    tags:
      - '*'
jobs:
  publish:
    name: Build, test and push image
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Define image name
        run: |
            IMAGE=${{ env.REGISTRY }}/acid/postgres-operator:${GITHUB_REF/refs\/tags\//}
            echo "NAME=$IMAGE" >> $GITHUB_OUTPUT

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to GHCR
        uses: docker/login-action@v2
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and export to local docker for testing
        uses: docker/build-push-action@v3
        with:
          context: "docker/"
          load: true
          build-args: BASE_IMAGE=alpine-3.15:latest
          tags: ${{ steps.image.outputs.NAME }}

      - name: Run unit tests
        run: make test

      - name: Build and push multiarch image to ghcr
        uses: docker/build-push-action@v3
        with:
          context: "docker/"
          push: true
          build-args: BASE_IMAGE=alpine-3.15:latest
          tags: "${{ steps.image.outputs.NAME }}"
          platforms: linux/amd64,linux/arm64
